// <auto-generated />
using System;
using Conecta.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Conecta.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20241114121756_SeedDataToRoleTable")]
    partial class SeedDataToRoleTable
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.10");

            modelBuilder.Entity("Conecta.Models.Role", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<DateTime?>("CreationDate")
                        .HasColumnType("TEXT")
                        .HasColumnName("creation_date");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT")
                        .HasColumnName("name");

                    b.Property<DateTime?>("UpdateDate")
                        .HasColumnType("TEXT")
                        .HasColumnName("update_date");

                    b.HasKey("Id");

                    b.ToTable("role");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreationDate = new DateTime(2024, 11, 14, 7, 17, 56, 546, DateTimeKind.Local).AddTicks(7350),
                            Name = "admin"
                        },
                        new
                        {
                            Id = 2,
                            CreationDate = new DateTime(2024, 11, 14, 7, 17, 56, 546, DateTimeKind.Local).AddTicks(7385),
                            Name = "user"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
